In [3]:
# Installez la librairie via : pip install understatapi
from understatapi import UnderstatClient

# Initialisation
understat = UnderstatClient()

# Récupération des données d'un championnat pour la saison 2025
# (Exemple pour la Premier League)
league_data = understat.league(league="EPL").get_player_data(season="2025")

# Cela renverra une liste de dictionnaires très propre avec 'xG', 'xA', etc.
import pandas as pd
df_xG = pd.DataFrame(league_data)
print(df_xG.head())

      id         player_name games  time goals                  xG assists  \
0   8260      Erling Haaland    35  2979    27  28.795336209237576       8
1  13222              Thiago    38  3292    22   24.68977300822735       1
2  11363     Antoine Semenyo    37  3220    17  12.836786897853017       4
3   8865       Ollie Watkins    37  2908    16  18.827725588344038       3
4   6857  Morgan Gibbs-White    37  3142    15  11.671697720885277       4

                   xA shots key_passes yellow_cards red_cards position  \
0   5.507687093690038   125         25            2         0      F S
1  3.4500465877354145    84         24            7         0      F S
2   4.130169393494725    83         38            7         0      F M
3   2.816021606326103    83         23            4         0      F S
4  4.5044658575206995    83         48            1         0    F M S

                    team_title npg                npxG             xGChain  \
0              Manchester City  24    25.7506607696414  32.735352732241154
1                    Brentford  14   17.83925338834524  22.693457752466202
2  Bournemouth,Manchester City  16   11.31444920040667  20.870588455349207
3                  Aston Villa  16  18.827725588344038  21.745904091745615
4            Nottingham Forest  14  10.910528883337975   17.26536614820361

            xGBuildup
0   5.163548586890101
1  4.9276386722922325
2   7.893717190250754
3  4.3408186649903655
4    5.41371457837522

In [4]:
df_xG.sample(20)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
121,11707,Jurriën Timber,30,2475,3,4.030840836465359,5,2.5891424333676696,25,28,5,0,D S,Arsenal,3,4.030840836465359,11.438589019700885,8.65939543582499
330,6080,Victor Lindelöf,17,938,0,0.15612759068608284,1,0.5980998799204826,3,2,0,0,D M S,Aston Villa,0,0.15612759068608284,2.5445900056511164,2.527874367311597
112,8864,Matthew Cash,35,3040,3,1.2179190125316381,3,3.2148889815434813,30,31,9,0,D S,Aston Villa,3,1.2179190125316381,10.301109017804265,8.072564328089356
9,11504,Eli Junior Kroupi,33,1708,13,8.849121669307351,0,1.81576990429312,52,22,5,0,F M S,Bournemouth,11,7.326783983036876,11.65668847411871,5.08306846767664
500,13724,Freddie Potts,22,1152,0,0.21263288706541061,1,1.2075103465467691,3,8,1,0,M S,West Ham,0,0.21263288706541061,3.1646942142397165,2.264735572040081
102,6837,Ryan Sessegnon,27,1830,3,2.04829409904778,1,2.2284331284463406,16,14,0,0,D M S,Fulham,3,2.04829409904778,8.259379532188177,5.088316984474659
356,7332,Max Kilman,21,1552,0,1.1671122973784804,0,0.20770752429962158,7,4,4,0,D S,West Ham,0,1.1671122973784804,1.233875660225749,1.128087779507041
503,13740,David Møller Wolfe,22,1059,0,0.08255818113684654,2,1.3046692535281181,3,8,1,0,D S,Wolverhampton Wanderers,0,0.08255818113684654,1.7902654558420181,1.2973200660198927
461,12359,Callum Marshall,2,44,0,0.2289344072341919,0,0,1,0,0,0,S,West Ham,0,0.2289344072341919,0,0
288,725,Ola Aina,18,1595,0,0.40960373170673847,0,0.34134200774133205,12,9,3,0,D,Nottingham Forest,0,0.40960373170673847,3.950665080919862,3.527306206524372
276,13741,Jhon Arias,23,1140,1,3.2931467425078154,0,0.8962265644222498,16,11,1,0,F M S,Wolverhampton Wanderers,1,3.2931467425078154,4.877626428380609,1.3450943380594254
67,11592,Nico O&#039;Reilly,34,2646,5,6.7270112708210945,3,3.847439743578434,41,23,5,0,D M S,Manchester City,5,6.7270112708210945,21.241205548867583,14.797816466540098
508,13835,Joël Piroe,16,216,0,1.0837035588920116,0,0.08580565452575684,14,1,0,0,F S,Leeds,0,1.0837035588920116,1.2039332054555416,0.21693582646548748
75,7365,Lucas Paquetá,18,1544,4,2.440835335291922,1,3.011969303712249,23,23,5,1,F M,West Ham,2,0.9184976601973176,4.265645559877157,1.5286574847996235
475,13094,Dário Essugo,3,24,0,0,0,0,0,0,2,0,S,Chelsea,0,0,0.43163326010107994,0.43163326010107994
283,585,Seamus Coleman,5,13,0,0,0,0.03790665417909622,0,1,0,0,D S,Everton,0,0,0.03790665417909622,0.03790665417909622
424,10802,Lisandro Martínez,18,1217,0,0.11346602533012629,0,0.46420332230627537,5,5,0,1,D S,Manchester United,0,0.11346602533012629,6.68968091532588,6.568602550774813
228,8853,Maxence Lacroix,35,3094,1,3.006834846921265,2,1.2868863735347986,25,7,4,1,D,Crystal Palace,1,3.006834846921265,10.744279656559229,9.981197169981897
55,13778,Igor Jesus,37,2379,6,7.199080093763769,4,2.280350387096405,70,15,2,0,F M S,Nottingham Forest,5,6.437911256216466,8.53495698235929,1.8483535712584853
511,14027,Veljko Milosavljevic,7,363,0,0.357437402009964,0,0.06701014190912247,1,1,0,0,D S,Bournemouth,0,0.357437402009964,0.45751750841736794,0.39050735905766487

In [5]:
from understatapi import UnderstatClient
import pandas as pd

# Liste des ligues que vous voulez analyser
ligues = ["EPL", "Bundesliga", "Serie_A", "Ligue_1", "La_Liga"]

understat = UnderstatClient()
all_data = []

# Boucle pour récupérer chaque championnat
for nom_ligue in ligues:
    print(f"Récupération de {nom_ligue}...")
    data = understat.league(league=nom_ligue).get_player_data(season="2025")
    
    # Transformation en DataFrame
    df_temp = pd.DataFrame(data)
    df_temp['league'] = nom_ligue # Très important pour ne pas mélanger les joueurs !
    all_data.append(df_temp)

# Fusionner le tout en un seul grand DataFrame
df_final = pd.concat(all_data, ignore_index=True)

# Résultat final
display(df_final.sample(20))

Récupération de EPL...
Récupération de Bundesliga...
Récupération de Serie_A...
Récupération de Ligue_1...
Récupération de La_Liga...

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,league
2229,11322,Viktor Tsygankov,32,2672,6,7.313595972955227,5,4.26087084133178,50,55,3,0,F M S,Girona,6,7.313595972955227,15.098643213510513,5.471966687589884,La_Liga
1688,12045,Aron Dønnum,28,2438,4,4.60387984290719,4,6.289067713543773,40,63,8,1,D F M,Toulouse,1,2.323594458401203,11.223862638697028,5.957076565362513,Ligue_1
700,10863,Aaron Zehnter,20,1467,2,1.8096191370859742,0,1.0538889579474926,11,16,0,0,D M S,Wolfsburg,2,1.8096191370859742,5.76640553586185,3.103568371385336,Bundesliga
435,11167,Chadi Riad,9,562,0,0.27994551230221987,1,0.42769163846969604,4,1,2,0,D S,Crystal Palace,0,0.27994551230221987,1.6205672025680542,1.5276411771774292,EPL
1693,13756,Santiago Hidalgo,28,1297,4,3.9984716661274433,6,2.7228170400485396,33,13,4,0,F M S,Toulouse,4,3.9984716661274433,6.639282990247011,2.0777887292206287,Ligue_1
2587,9024,Yeremi Pino,2,165,0,0.12507127225399017,1,0.8602673262357712,2,6,0,0,M,Villarreal,0,0.12507127225399017,2.0280728340148926,1.4558568000793457,La_Liga
1698,5598,Angel Gomes,14,919,3,2.0597879961133003,0,1.0676721185445786,11,18,4,0,M S,Marseille,3,2.0597879961133003,7.522297575138509,4.833005172200501,Ligue_1
650,11840,Jovan Milosevic,13,476,3,2.319580804556608,1,0.24364536255598068,12,3,2,0,F S,Werder Bremen,3,2.319580804556608,2.8273107409477234,0.4218983128666878,Bundesliga
1557,13504,Matteo Cocchi,1,14,0,0,0,0,0,0,0,0,S,Inter,0,0,0,0,Serie_A
898,9916,Finley Stevens,1,25,0,0,0,0,0,0,0,0,S,St. Pauli,0,0,0.041828397661447525,0.041828397661447525,Bundesliga
1543,13340,Luka Topalovic,1,7,0,0,1,0.15691280364990234,0,1,0,0,S,Inter,0,0,0.15691280364990234,0,Serie_A
204,6369,Ethan Ampadu,35,3130,1,1.946105619892478,1,1.1763546681031585,26,19,10,0,M,Leeds,1,1.946105619892478,11.866393697448075,10.690290067344904,EPL
2655,12472,Iñigo Arguibide,6,187,0,0,0,0.03171418979763985,0,1,0,1,D S,Osasuna,0,0,0.13765155244618654,0.1059373626485467,La_Liga
1451,9090,Ardian Ismajli,25,1907,0,0.7488318141549826,1,0.5390323810279369,6,4,5,0,D S,Torino,0,0.7488318141549826,3.390311038121581,2.8379868511110544,Serie_A
945,12761,Yukinari Sugawara,31,2444,0,1.6741932658478618,6,2.4432157278060913,30,20,2,1,D S,Werder Bremen,0,1.6741932658478618,8.13111265283078,5.448099664412439,Bundesliga
2768,14519,Ville Koski,5,281,0,0.01684470660984516,0,0.06809491664171219,1,1,0,0,D S,Alaves,0,0.01684470660984516,0.02529877983033657,0.02529877983033657,La_Liga
834,4376,Marvin Schwäbe,34,3060,0,0,0,0.36419060826301575,0,1,2,0,GK,FC Cologne,0,0,5.936441767960787,5.572251129895449,Bundesliga
1000,13972,Andrija Maksimovic,8,77,0,0.0663988795131445,0,0.3666895739734173,2,3,0,0,S,RasenBallsport Leipzig,0,0.0663988795131445,0.42848074436187744,0.40251037664711475,Bundesliga
2429,12182,Jon Aramburu,35,2789,1,2.057084806263447,0,0.4437111411243677,21,11,11,0,D S,Real Sociedad,1,2.057084806263447,6.378528879955411,5.833133289590478,La_Liga
1768,11798,Koffi Kouao,27,2296,2,1.6477266969159245,1,1.2461658138781786,23,11,10,0,D,Metz,2,1.6477266969159245,5.849459524266422,3.4310527173802257,Ligue_1

In [6]:
df_mbappe = df_final[df_final['player_name'] == 'Ousmane Dembélé']
df_mbappe

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,league
1634,3226,Ousmane Dembélé,22,1050,10,6.604901619255543,7,5.207486420869827,45,41,0,0,F S,Paris Saint Germain,8,4.324616186320782,10.21094974130392,4.470038652420044,Ligue_1

In [7]:
df_final.columns

Index(['id', 'player_name', 'games', 'time', 'goals', 'xG', 'assists', 'xA',
       'shots', 'key_passes', 'yellow_cards', 'red_cards', 'position',
       'team_title', 'npg', 'npxG', 'xGChain', 'xGBuildup', 'league'],
      dtype='str')

In [8]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 2775 entries, 0 to 2774
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            2775 non-null   str
 1   player_name   2775 non-null   str
 2   games         2775 non-null   str
 3   time          2775 non-null   str
 4   goals         2775 non-null   str
 5   xG            2775 non-null   str
 6   assists       2775 non-null   str
 7   xA            2775 non-null   str
 8   shots         2775 non-null   str
 9   key_passes    2775 non-null   str
 10  yellow_cards  2775 non-null   str
 11  red_cards     2775 non-null   str
 12  position      2775 non-null   str
 13  team_title    2775 non-null   str
 14  npg           2775 non-null   str
 15  npxG          2775 non-null   str
 16  xGChain       2775 non-null   str
 17  xGBuildup     2775 non-null   str
 18  league        2775 non-null   str
dtypes: str(19)
memory usage: 761.0 KB

In [9]:
# Liste des colonnes qui DOIVENT rester du texte
colonnes_texte = ['player_name', 'team_title', 'league', 'position']

# Conversion de tout le reste en numérique
for col in df_final.columns:
    if col not in colonnes_texte:
        # 'coerce' transforme les erreurs (ex: 'N/A') en NaN (valeurs vides)
        df_final[col] = pd.to_numeric(df_final[col], errors='coerce')

# Vérification
print(df_final.info())

<class 'pandas.DataFrame'>
RangeIndex: 2775 entries, 0 to 2774
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            2775 non-null   int64
 1   player_name   2775 non-null   str
 2   games         2775 non-null   int64
 3   time          2775 non-null   int64
 4   goals         2775 non-null   int64
 5   xG            2775 non-null   float64
 6   assists       2775 non-null   int64
 7   xA            2775 non-null   float64
 8   shots         2775 non-null   int64
 9   key_passes    2775 non-null   int64
 10  yellow_cards  2775 non-null   int64
 11  red_cards     2775 non-null   int64
 12  position      2775 non-null   str
 13  team_title    2775 non-null   str
 14  npg           2775 non-null   int64
 15  npxG          2775 non-null   float64
 16  xGChain       2775 non-null   float64
 17  xGBuildup     2775 non-null   float64
 18  league        2775 non-null   str
dtypes: float64(5), int64(10), str(4)
memory usage: 502.2 KB
None

In [10]:
df_joueurs = pd.read_csv('../data/players_photo.csv')
df_joueurs

,player_id,player_name,team,team_crest,position,dob,nationality,photo_url
0,3160,Fernando Muslera,Uruguay,https://crests.football-data.org/758.svg,Goalkeeper,1986-06-16,Uruguay,https://img.a.transfermarkt.technology/portrai...
1,30210,Santiago Mele,Uruguay,https://crests.football-data.org/758.svg,Goalkeeper,1997-09-06,Uruguay,https://img.a.transfermarkt.technology/portrai...
2,30386,Sergio Rochet,Uruguay,https://crests.football-data.org/758.svg,Goalkeeper,1993-03-23,Uruguay,https://img.a.transfermarkt.technology/portrai...
3,3165,Guillermo Varela,Uruguay,https://crests.football-data.org/758.svg,Defence,1993-03-24,Uruguay,https://img.a.transfermarkt.technology/portrai...
4,28292,Ronald Araújo,Uruguay,https://crests.football-data.org/758.svg,Defence,1999-03-07,Uruguay,https://img.a.transfermarkt.technology/portrai...
...,...,...,...,...,...,...,...,...
1208,98483,Tahith Chong,Curaçao,https://crests.football-data.org/curacao.svg,Offence,1999-12-04,Curaçao,https://img.a.transfermarkt.technology/portrai...
1209,137025,Sontje Hansen,Curaçao,https://crests.football-data.org/curacao.svg,Offence,2002-05-18,Curaçao,https://img.a.transfermarkt.technology/portrai...
1210,149134,Jearl Margaritha,Curaçao,https://crests.football-data.org/curacao.svg,Offence,2000-04-10,Curaçao,https://img.a.transfermarkt.technology/portrai...
1211,156631,Jeremy Antonisse,Curaçao,https://crests.football-data.org/curacao.svg,Offence,2002-03-29,Curaçao,https://img.a.transfermarkt.technology/portrai...
1212,190770,Brandley Kuwas,Curaçao,https://crests.football-data.org/curacao.svg,Offence,1992-09-19,Curaçao,https://img.a.transfermarkt.technology/portrai...

In [11]:
df_joueurs.info()
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 1213 entries, 0 to 1212
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   player_id    1213 non-null   int64
 1   player_name  1213 non-null   str
 2   team         1213 non-null   str
 3   team_crest   1213 non-null   str
 4   position     1213 non-null   str
 5   dob          1212 non-null   str
 6   nationality  1211 non-null   str
 7   photo_url    1138 non-null   str
dtypes: int64(1), str(7)
memory usage: 267.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 2775 entries, 0 to 2774
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            2775 non-null   int64
 1   player_name   2775 non-null   str
 2   games         2775 non-null   int64
 3   time          2775 non-null   int64
 4   goals         2775 non-null   int64
 5   xG            2775 non-null   float64
 6   assists       2775 non-null   int64
 7   xA            2775 non-null   float64
 8   shots         2775 non-null   int64
 9   key_passes    2775 non-null   int64
 10  yellow_cards  2775 non-null   int64
 11  red_cards     2775 non-null   int64
 12  position      2775 non-null   str
 13  team_title    2775 non-null   str
 14  npg           2775 non-null   int64
 15  npxG          2775 non-null   float64
 16  xGChain       2775 non-null   float64
 17  xGBuildup     2775 non-null   float64
 18  league        2775 non-null   str
dtypes: float64(5), int64(10), str(4)
memory usage: 502.2 KB

In [12]:
df_final.to_csv('mon_fichier_final.csv', index=False)

In [13]:

df_joueurs.sample(10)

,player_id,player_name,team,team_crest,position,dob,nationality,photo_url
1099,149716,Akmal Mozgovoy,Uzbekistan,https://crests.football-data.org/8070.png,Midfield,2000-04-02,Uzbekistan,https://img.a.transfermarkt.technology/portrai...
879,244158,Ariya Yousefi,Iran,https://crests.football-data.org/iran.svg,Midfield,2002-04-22,Iran,NaN
501,24670,Alan Franco,Ecuador,https://crests.football-data.org/791.svg,Midfield,1998-08-21,Ecuador,https://img.a.transfermarkt.technology/portrai...
469,2114,Silvan Widmer,Switzerland,https://crests.football-data.org/788.svg,Defence,1993-03-05,Switzerland,https://img.a.transfermarkt.technology/portrai...
625,3608,Ellyes Skhiri,Tunisia,https://crests.football-data.org/tunisia.svg,Midfield,1995-05-10,Tunisia,https://img.a.transfermarkt.technology/portrai...
41,101074,Felix Kalu Nmecha,Germany,https://crests.football-data.org/759.svg,Midfield,2000-10-10,Germany,https://img.a.transfermarkt.technology/portrai...
894,17869,Nihad Mujakić,Bosnia-Herzegovina,https://crests.football-data.org/bosnia.svg,Defence,1998-04-15,Bosnia-Herzegovina,https://img.a.transfermarkt.technology/portrai...
1018,277484,Yan Diomandé,Ivory Coast,https://crests.football-data.org/787.svg,Offence,2006-11-14,Ivory Coast,https://img.a.transfermarkt.technology/portrai...
926,253717,Edgardo Fariña,Panama,https://crests.football-data.org/panama.svg,Defence,2001-09-21,Panama,https://img.a.transfermarkt.technology/portrai...
253,39237,Julián Quiñones,Mexico,https://crests.football-data.org/769.svg,Offence,1997-03-24,Colombia,https://img.a.transfermarkt.technology/portrai...

In [21]:
df_final.sample(10)

,id,player_name_stats,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position_stats,team_title,npg,npxG,xGChain,xGBuildup,league,player_clean
1293,11306,Cyril Ngonge,20,987,1,2.762548,1,0.562379,24,12,2,0,F S,Torino,1,2.762548,4.732534,1.595636,Serie_A,cyril ngonge
533,14425,Melker Ellborg,3,270,0,0.000000,0,0.000000,0,0,0,0,GK,Sunderland,0,0.000000,0.101297,0.101297,EPL,melker ellborg
117,10807,Jan Paul van Hecke,36,3214,3,3.358579,3,1.025566,23,12,9,0,D,Brighton,3,3.358579,14.122218,13.213501,EPL,jan paul van hecke
1332,14351,Rafiu Durosinmi,12,428,1,0.759808,1,0.087608,9,3,1,1,F S,Pisa,1,0.759808,0.926448,0.182712,Serie_A,rafiu durosinmi
2508,4091,Unai López,28,1637,0,1.007179,4,2.520821,22,36,6,1,M S,Rayo Vallecano,0,1.007179,7.014564,5.052039,La_Liga,unai lopez
1646,6905,Ludovic Ajorque,32,2834,8,9.856391,9,3.817547,55,41,9,1,F,Brest,8,9.856391,16.418826,5.105777,Ligue_1,ludovic ajorque
1425,8241,Balthazar Pierret,3,20,0,0.000000,0,0.000000,0,0,0,0,S,Lecce,0,0.000000,0.000000,0.000000,Serie_A,balthazar pierret
1928,5732,Abdoulaye Bamba,6,255,0,0.014829,0,0.000000,1,0,1,0,D S,Angers,0,0.014829,0.384024,0.369194,Ligue_1,abdoulaye bamba
2227,9211,Nico Williams,25,1715,6,5.862555,3,4.138544,46,34,2,0,M S,Athletic Club,5,4.376000,10.798388,3.284014,La_Liga,nico williams
2481,2090,Marc-André ter Stegen,2,180,0,0.000000,0,0.000000,0,0,0,0,GK,Girona,0,0.000000,0.024570,0.024570,La_Liga,marcandre ter stegen

In [15]:
import pandas as pd
import numpy as np
import unicodedata
import re

# ============================================================
# 1. CHARGEMENT DES DATASETS
# ============================================================

print("df_joueurs :", df_joueurs.shape)
print("df_final   :", df_final.shape)


# ============================================================
# 2. NORMALISATION DES NOMS (clé de merge)
# ============================================================

def normalize_name(name):
    """Lowercase, supprime accents, retire caractères spéciaux."""
    if pd.isna(name):
        return np.nan
    name = str(name).lower().strip()
    name = unicodedata.normalize("NFD", name)
    name = "".join(c for c in name if unicodedata.category(c) != "Mn")
    name = re.sub(r"[^a-z\s]", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name

df_joueurs["player_clean"] = df_joueurs["player_name"].apply(normalize_name)
df_final["player_clean"]   = df_final["player_name"].apply(normalize_name)


# ============================================================
# 3. VÉRIFICATION DU TAUX DE MATCHING
# ============================================================

joueurs_set = set(df_joueurs["player_clean"].dropna())
final_set   = set(df_final["player_clean"].dropna())

communs     = joueurs_set & final_set
sans_stats  = joueurs_set - final_set
sans_joueur = final_set - joueurs_set

print(f"\nJoueurs en commun         : {len(communs)}")
print(f"Joueurs sans stats xG     : {len(sans_stats)}")
print(f"Stats xG sans fiche joueur: {len(sans_joueur)}")


# ============================================================
# 4. NETTOYAGE PRÉ-MERGE — résoudre les conflits de colonnes
# ============================================================

# 'position' existe dans les deux → renommer celle de df_final
df_final = df_final.rename(columns={
    "position"    : "position_stats",
    "player_name" : "player_name_stats"   # éviter le doublon _x/_y
})


# ============================================================
# 5. MERGE
# ============================================================

df_merged = pd.merge(
    df_joueurs,
    df_final,
    on="player_clean",
    how="left"    # ← garde tous les joueurs ; change en "inner" pour le modèle
)

print(f"\nDataset mergé : {df_merged.shape}")


# ============================================================
# 6. NETTOYAGE POST-MERGE
# ============================================================

# Supprimer player_name_stats (doublon) et l'id de df_final
df_merged = df_merged.drop(columns=["player_name_stats", "id"], errors="ignore")

# Réordonner les colonnes
cols_info  = ["player_id", "player_name", "player_clean", "team", "team_crest",
              "position", "dob", "nationality", "photo_url"]
cols_stats = ["games", "time", "goals", "xG", "assists", "xA", "shots",
              "key_passes", "yellow_cards", "red_cards", "position_stats",
              "team_title", "npg", "npxG", "xGChain", "xGBuildup", "league"]

cols_info  = [c for c in cols_info  if c in df_merged.columns]
cols_stats = [c for c in cols_stats if c in df_merged.columns]

df_merged = df_merged[cols_info + cols_stats]


# ============================================================
# 7. DATASET POUR LE MODÈLE DE PRÉDICTION
# ============================================================

# Uniquement les joueurs avec des stats xG complètes
df_model = df_merged.dropna(subset=["xG", "xA"]).copy()

print(f"\nDataset modèle : {df_model.shape}")

# Top 10 buteurs potentiels (xG)
print("\n--- Top 10 buteurs potentiels (xG) ---")
print(
    df_model[["player_name", "team", "xG", "npxG", "shots", "goals"]]
    .sort_values("xG", ascending=False)
    .head(10)
    .to_string(index=False)
)

# Top 10 passeurs potentiels (xA)
print("\n--- Top 10 passeurs potentiels (xA) ---")
print(
    df_model[["player_name", "team", "xA", "key_passes", "assists"]]
    .sort_values("xA", ascending=False)
    .head(10)
    .to_string(index=False)
)


# ============================================================
# 8. EXPORT
# ============================================================

df_merged.to_csv("df_merged_complet.csv", index=False)
df_model.to_csv("df_model_prediction.csv", index=False)

print("\n✅ Fichiers exportés :")
print("   → df_merged_complet.csv   (tous les joueurs)")
print("   → df_model_prediction.csv (joueurs avec stats xG, prêts pour le modèle)")

df_joueurs : (1213, 8)
df_final   : (2775, 19)

Joueurs en commun         : 449
Joueurs sans stats xG     : 763
Stats xG sans fiche joueur: 2240

Dataset mergé : (1230, 28)

Dataset modèle : (467, 26)

--- Top 10 buteurs potentiels (xG) ---
          player_name      team        xG      npxG  shots  goals
           Harry Kane   England 29.579986 21.244442  119.0   36.0
       Erling Haaland    Norway 28.795336 25.750661  125.0   27.0
               Thiago    Brazil 24.689773 17.839253   84.0   22.0
        Patrik Schick   Czechia 19.421328 15.632445   72.0   16.0
         Ante Budimir   Croatia 19.191765 13.245544  103.0   17.0
          Deniz Undav   Germany 19.057547 18.299771  124.0   19.0
        Ollie Watkins   England 18.827726 18.827726   83.0   16.0
Christoph Baumgartner   Austria 18.022841 17.265064   81.0   13.0
     Lautaro Martínez Argentina 17.138830 17.138830   92.0   17.0
        Ferrán Torres     Spain 16.183372 16.183372   69.0   16.0

--- Top 10 passeurs potentiels (xA) ---
         player_name        team        xA  key_passes  assists
     Bruno Fernandes    Portugal 17.757135       137.0     21.0
       Michael Olise      France 17.044203        79.0     19.0
        Lamine Yamal       Spain 12.566995        73.0     11.0
          David Raum     Germany 11.038922        96.0      7.0
      Julian Ryerson      Norway 10.857276        57.0     15.0
Charles De Ketelaere     Belgium 10.652647        64.0      5.0
       Romano Schmid     Austria 10.276879        87.0      8.0
           Luis Díaz    Colombia 10.122724        65.0     14.0
        Yan Diomandé Ivory Coast 10.048876        57.0      8.0
      Enzo Fernández   Argentina  8.865935        68.0      4.0

✅ Fichiers exportés :
   → df_merged_complet.csv   (tous les joueurs)
   → df_model_prediction.csv (joueurs avec stats xG, prêts pour le modèle)

In [22]:
# Chercher Mbappé dans df_final
df_final[df_final["player_name_stats"].str.contains("mbappe|mbapp|kylian", case=False, na=False)]

,id,player_name_stats,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position_stats,team_title,npg,npxG,xGChain,xGBuildup,league,player_clean
1719,12066,Ethan Mbappé,18,530,3,1.866912,1,1.491426,14,15,1,0,F M S,Lille,3,1.866912,3.409807,1.001054,Ligue_1,ethan mbappe
2175,3423,Kylian Mbappe-Lottin,31,2623,25,25.796529,5,7.240632,146,65,4,0,F S,Real Madrid,17,19.107030,27.866945,7.233588,La_Liga,kylian mbappelottin

In [20]:
print(df_final.columns.tolist())

['id', 'player_name_stats', 'games', 'time', 'goals', 'xG', 'assists', 'xA', 'shots', 'key_passes', 'yellow_cards', 'red_cards', 'position_stats', 'team_title', 'npg', 'npxG', 'xGChain', 'xGBuildup', 'league', 'player_clean']

In [23]:
corrections = {
    "kylian mbappelottin" : "kylian mbappe",
    "kylian mbappe lottin": "kylian mbappe",
    # tu peux en ajouter d'autres au fur et à mesure
}

df_final["player_clean"] = df_final["player_clean"].replace(corrections)

In [25]:
df_final[df_final["player_clean"] == "kylian mbappe"]

,id,player_name_stats,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position_stats,team_title,npg,npxG,xGChain,xGBuildup,league,player_clean
2175,3423,Kylian Mbappe-Lottin,31,2623,25,25.796529,5,7.240632,146,65,4,0,F S,Real Madrid,17,19.10703,27.866945,7.233588,La_Liga,kylian mbappe

In [26]:
df_joueurs[df_joueurs["player_name"].str.contains("mbappe|kylian", case=False, na=False)]

,player_id,player_name,team,team_crest,position,dob,nationality,photo_url,player_clean
359,3374,Kylian Mbappé,France,https://crests.football-data.org/773.svg,Offence,1998-12-20,France,https://img.a.transfermarkt.technology/portrai...,kylian mbappe

In [27]:
df_merged = pd.merge(
    df_joueurs,
    df_final,
    on="player_clean",
    how="left"
)

In [28]:
df_merged.to_csv("df_merged_complet.csv", index=False)
df_model = df_merged.dropna(subset=["xG", "xA"]).copy()
df_model.to_csv("df_model_prediction.csv", index=False)

In [29]:
# Vérifier Mbappé
print(df_merged[df_merged["player_clean"] == "kylian mbappe"][
    ["player_name", "team", "xG", "goals", "assists", "xA", "photo_url"]
])

       player_name    team         xG  goals  assists        xA  \
367  Kylian Mbappé  France  25.796529   25.0      5.0  7.240632

                                             photo_url
367  https://img.a.transfermarkt.technology/portrai...

In [30]:
joueurs_cles = ["kylian mbappe", "lionel messi", "cristiano ronaldo", 
                "luka modric", "erling haaland"]

for j in joueurs_cles:
    row = df_merged[df_merged["player_clean"] == j]
    if len(row) > 0:
        r = row.iloc[0]
        print(f"✅ {r['player_name']} — xG: {r.get('xG', 'N/A')} | buts: {r.get('goals', 'N/A')} | photo: {'✅' if pd.notna(r.get('photo_url')) else '❌'}")
    else:
        print(f"❌ {j} — toujours absent")

✅ Kylian Mbappé — xG: 25.796528611332175 | buts: 25.0 | photo: ✅
✅ Lionel Messi — xG: nan | buts: nan | photo: ✅
✅ Cristiano Ronaldo — xG: nan | buts: nan | photo: ✅
✅ Luka Modrić — xG: 1.2469155695289371 | buts: 2.0 | photo: ✅
✅ Erling Haaland — xG: 28.795336209237576 | buts: 27.0 | photo: ✅

In [94]:
corrections_canada = [
    {
        "player_clean": "jonathan david",
        "goals": 6, "xG": 8.2, "assists": 4, "xA": 3.8,
        "shots": 41, "key_passes": 28, "games": 35, "time": 1782,
        "npxG": 6.2, "team_title": "Juventus", "league": "Serie_A",
        "yellow_cards": 0, "red_cards": 0
    },
    {
        "player_clean": "cyle larin",
        "goals": 7, "xG": 5.8, "assists": 1, "xA": 1.2,
        "shots": 18, "key_passes": 8, "games": 15, "time": 830,
        "npxG": 5.2, "team_title": "Southampton", "league": "Championship",
        "yellow_cards": 1, "red_cards": 0
    },
    {
        "player_clean": "stephen eustaquio",
        "goals": 3, "xG": 2.8, "assists": 5, "xA": 4.2,
        "shots": 28, "key_passes": 42, "games": 26, "time": 2100,
        "npxG": 2.6, "team_title": "LAFC", "league": "MLS",
        "yellow_cards": 4, "red_cards": 0
    },
    {
        "player_clean": "mathieu choiniere",
        "goals": 4, "xG": 3.5, "assists": 5, "xA": 4.0,
        "shots": 32, "key_passes": 35, "games": 24, "time": 1820,
        "npxG": 3.2, "team_title": "LAFC", "league": "MLS",
        "yellow_cards": 2, "red_cards": 0
    },
    {
        "player_clean": "jonathan osorio",
        "goals": 3, "xG": 2.5, "assists": 4, "xA": 3.2,
        "shots": 22, "key_passes": 28, "games": 22, "time": 1650,
        "npxG": 2.4, "team_title": "Toronto FC", "league": "MLS",
        "yellow_cards": 3, "red_cards": 0
    },
    {
        "player_clean": "liam millar",
        "goals": 6, "xG": 5.2, "assists": 4, "xA": 3.5,
        "shots": 38, "key_passes": 26, "games": 28, "time": 2050,
        "npxG": 4.8, "team_title": "Hull City", "league": "Championship",
        "yellow_cards": 2, "red_cards": 0
    },
    {
        "player_clean": "jacob shaffelburg",
        "goals": 4, "xG": 3.6, "assists": 2, "xA": 2.0,
        "shots": 28, "key_passes": 18, "games": 23, "time": 1117,
        "npxG": 3.4, "team_title": "LAFC", "league": "MLS",
        "yellow_cards": 1, "red_cards": 0
    },
    {
        "player_clean": "ali ahmed",
        "goals": 5, "xG": 4.2, "assists": 6, "xA": 5.0,
        "shots": 35, "key_passes": 38, "games": 25, "time": 1900,
        "npxG": 3.9, "team_title": "Norwich City", "league": "Championship",
        "yellow_cards": 2, "red_cards": 0
    },
    {
        "player_clean": "marcelo flores",
        "goals": 4, "xG": 3.8, "assists": 5, "xA": 4.2,
        "shots": 30, "key_passes": 32, "games": 22, "time": 1650,
        "npxG": 3.5, "team_title": "Tigres UANL", "league": "Liga_MX",
        "yellow_cards": 2, "red_cards": 0
    },
    {
        "player_clean": "nathan dylan saliba",
        "goals": 2, "xG": 1.8, "assists": 3, "xA": 2.5,
        "shots": 18, "key_passes": 22, "games": 20, "time": 1450,
        "npxG": 1.7, "team_title": "Anderlecht", "league": "Jupiler_Pro",
        "yellow_cards": 3, "red_cards": 0
    },
    {
        "player_clean": "promise akinpelu",
        "goals": 5, "xG": 4.5, "assists": 3, "xA": 2.8,
        "shots": 32, "key_passes": 18, "games": 22, "time": 1680,
        "npxG": 4.2, "team_title": "Union Saint-Gilloise", "league": "Jupiler_Pro",
        "yellow_cards": 2, "red_cards": 0
    },
]

for correction in corrections_canada:
    nom = correction["player_clean"]
    mask = df_merged["player_clean"] == nom

    if mask.sum() == 0:
        print(f"❌ {nom} — introuvable, vérifie le player_clean")
        continue

    for col, val in correction.items():
        if col == "player_clean":
            continue
        if col in df_merged.columns:
            df_merged.loc[mask, col] = val

    row = df_merged[mask].iloc[0]
    print(f"✅ {row['player_name']} — xG: {correction['xG']} | buts: {correction['goals']}")

df_merged.to_csv("df_merged_complet.csv", index=False)
df_model = df_merged.dropna(subset=["xG", "xA"]).copy()
df_model.to_csv("df_model_prediction.csv", index=False)
print(f"\n✅ {len(df_model)} joueurs avec stats xG")

✅ Jonathan David — xG: 8.2 | buts: 6
✅ Cyle Larin — xG: 5.8 | buts: 7
✅ Stephen Eustáquio — xG: 2.8 | buts: 3
✅ Mathieu Choinière — xG: 3.5 | buts: 4
✅ Jonathan Osorio — xG: 2.5 | buts: 3
✅ Liam Millar — xG: 5.2 | buts: 6
✅ Jacob Shaffelburg — xG: 3.6 | buts: 4
✅ Ali Ahmed — xG: 4.2 | buts: 5
✅ Marcelo Flores — xG: 3.8 | buts: 4
❌ nathan dylan saliba — introuvable, vérifie le player_clean
✅ Promise Akinpelu — xG: 4.5 | buts: 5

✅ 494 joueurs avec stats xG

In [101]:
corrections_maroc = [
    {
        "player_clean": "azzedine ounahi",
        "goals": 5, "xG": 6.6, "assists": 2, "xA": 3.2,
        "shots": 51, "key_passes": 28, "games": 24, "time": 1187,
        "npxG": 6.6, "team_title": "Girona", "league": "La_Liga",
        "yellow_cards": 6, "red_cards": 0
    },
    {
        "player_clean": "ismael saibari",
        "goals": 15, "xG": 13.8, "assists": 8, "xA": 6.5,
        "shots": 91, "key_passes": 48, "games": 27, "time": 2147,
        "npxG": 13.2, "team_title": "PSV Eindhoven", "league": "Eredivisie",
        "yellow_cards": 2, "red_cards": 0
    },
    {
        "player_clean": "ayoub el kaabi",
        "goals": 18, "xG": 15.1, "assists": 2, "xA": 2.2,
        "shots": 90, "key_passes": 18, "games": 28, "time": 2109,
        "npxG": 15.1, "team_title": "Olympiacos", "league": "Super_League_Greece",
        "yellow_cards": 2, "red_cards": 0
    },
    {
        "player_clean": "soufiane rahimi",
        "goals": 9, "xG": 9.4, "assists": 2, "xA": 2.8,
        "shots": 57, "key_passes": 28, "games": 16, "time": 1240,
        "npxG": 9.4, "team_title": "Al Ain", "league": "Arabian_Gulf_League",
        "yellow_cards": 1, "red_cards": 0
    },
]

for correction in corrections_maroc:
    nom = correction["player_clean"]
    mask = df_merged["player_clean"] == nom

    if mask.sum() == 0:
        print(f"❌ {nom} — introuvable, vérifie le player_clean")
        continue

    for col, val in correction.items():
        if col == "player_clean":
            continue
        if col in df_merged.columns:
            df_merged.loc[mask, col] = val

    row = df_merged[mask].iloc[0]
    print(f"✅ {row['player_name']} — xG: {correction['xG']} | buts: {correction['goals']}")

df_merged.to_csv("df_merged_complet.csv", index=False)
df_model = df_merged.dropna(subset=["xG", "xA"]).copy()
df_model.to_csv("df_model_prediction.csv", index=False)
print(f"\n✅ {len(df_model)} joueurs avec stats xG")

✅ Azzedine Ounahi — xG: 6.6 | buts: 5
✅ Ismael Saibari — xG: 13.8 | buts: 15
✅ Ayoub El Kaabi — xG: 15.1 | buts: 18
✅ Soufiane Rahimi — xG: 9.4 | buts: 9

✅ 498 joueurs avec stats xG

In [114]:
# 1. Diagnostic : Regarder tous les joueurs qui contiennent "man" dans leur nom
# Cela permet de voir s'il est déjà là sous un autre nom (ex: "s. mane" ou "sadio")
recherche = df_merged[df_merged["player_clean"].str.contains("man", na=False, case=False)]
print("🔍 Joueurs trouvés avec 'man' dans le nom :")
print(recherche[["player_name", "player_clean"]])

# 2. Ajout forcé (si tu ne le vois pas dans la liste ci-dessus)
if "sadio mane" not in df_merged["player_clean"].values:
    print("\n⚠️ Sadio Mané introuvable. Ajout en cours...")
    
    # Création d'un dictionnaire avec toutes les colonnes nécessaires
    # Assure-toi que les noms de colonnes correspondent exactement aux tiennes
    nouveau_joueur = {
        "player_clean": "sadio mane",
        "player_name": "Sadio Mané",
        "goals": 10, "xG": 9.2, "assists": 6, "xA": 5.4,
        "shots": 61, "key_passes": 51, "games": 25, "time": 2132,
        "npxG": 9.2, "team_title": "Al Nassr", "league": "Saudi_Pro",
        "yellow_cards": 6, "red_cards": 0,
        "team_national": "Senegal" # Ajout de la colonne équipe nationale
    }
    
    # Ajout
    df_merged = pd.concat([df_merged, pd.DataFrame([nouveau_joueur])], ignore_index=True)
    print("✅ Sadio Mané ajouté avec succès !")
else:
    # Si on l'a trouvé, on s'assure que l'équipe est bien "Senegal"
    df_merged.loc[df_merged["player_clean"] == "sadio mane", "team_national"] = "Senegal"
    print("\n✅ Sadio Mané était déjà présent, équipe nationale mise à jour.")

# 3. Vérification finale
print("\n📋 Vérification de l'entrée :")
print(df_merged[df_merged["player_clean"] == "sadio mane"][["player_name", "team_national", "team_title"]])

🔍 Joueurs trouvés avec 'man' dans le nom :
              player_name         player_clean
15          Manuel Ugarte        manuel ugarte
26         Oliver Baumann       oliver baumann
27           Manuel Neuer         manuel neuer
127     José Manuel López    jose manuel lopez
132     Abdul Rahman Baba    abdul rahman baba
150   Kamal Deen Sulemana  kamal deen sulemana
258      Armando González     armando gonzalez
296          Alex Freeman         alex freeman
304         Malik Tillman        malik tillman
351             Manu Koné            manu kone
357       Ousmane Dembélé      ousmane dembele
373     Khulumani Ndamane    khulumani ndamane
391           Aïssa Mandi          aissa mandi
447           Finn Surman          finn surman
466         Manuel Akanji        manuel akanji
483        Johan Manzambi       johan manzambi
526      Herman Johansson     herman johansson
605           Ayman Yahya          ayman yahya
608        Sultan Mandash       sultan mandash
626      Anis Ben Slimane     anis ben slimane
683         Iliman Ndiaye        iliman ndiaye
704       Youri Tielemans      youri tielemans
758         Romano Schmid        romano schmid
817          Owen Goodman         owen goodman
821         Joel Waterman        joel waterman
866        Payam Niazmand       payam niazmand
886         Saman Ghoddos        saman ghoddos
921        César Blackman       cesar blackman
929      Cecilio Waterman     cecilio waterman
1000     Emmanuel Agbadou     emmanuel agbadou
1002     Ousmane Diomande     ousmane diomande
1016      Bazoumana Touré      bazoumana toure
1017         Yan Diomandé         yan diomande
1070         Manaf Younis         manaf younis
1191       Armando Obispo       armando obispo
1212           Sadio Mané           sadio mane

✅ Sadio Mané était déjà présent, équipe nationale mise à jour.

📋 Vérification de l'entrée :
     player_name team_national team_title
1212  Sadio Mané       Senegal   Al Nassr

In [116]:
# Filtrer et afficher tous les joueurs de l'équipe du Sénégal
senegal_team = df_merged[df_merged["team_national"] == "Senegal"]

print("📋 Liste actuelle de l'équipe du Sénégal :")
# Affiche le nom, l'équipe nationale et le club pour vérifier
print(senegal_team[["player_name", "team_national", "team_title"]])

📋 Liste actuelle de l'équipe du Sénégal :
     player_name team_national team_title
1212  Sadio Mané       Senegal   Al Nassr

In [118]:
# 1. On cherche spécifiquement Sadio Mané dans tout le DataFrame
resultat_mane = df_merged[df_merged["player_clean"] == "sadio mane"]

# 2. On affiche le résultat pour confirmer
print("🔍 Recherche spécifique de Sadio Mané :")
print(resultat_mane[["player_name", "team_national", "team_title", "xG", "goals"]])

# 3. Pour voir tous les Sénégalais, on filtre correctement
# On s'assure que 'team_national' est bien défini pour lui
senegalais = df_merged[df_merged["team_national"] == "Senegal"]

print("\n📋 Liste complète des joueurs du Sénégal :")
print(senegalais[["player_name", "team_national", "team_title"]])

🔍 Recherche spécifique de Sadio Mané :
     player_name team_national team_title   xG  goals
1212  Sadio Mané       Senegal   Al Nassr  9.2   10.0

📋 Liste complète des joueurs du Sénégal :
     player_name team_national team_title
1212  Sadio Mané       Senegal   Al Nassr

In [119]:
# 1. Normaliser la colonne pour supprimer les accents et mettre en minuscules
# Cela rendra tous tes filtres beaucoup plus robustes
df_merged['team_national_clean'] = df_merged['team_national'].astype(str).str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8').str.lower()

# 2. Vérifier comment "Sénégal" est écrit actuellement
print("Valeurs uniques dans team_national :")
print(df_merged['team_national'].unique())

# 3. Ré-appliquer l'équipe "Senegal" à tout le monde proprement
# Si tu veux que tout le monde soit sous le format "senegal"
df_merged.loc[df_merged['team_national_clean'].str.contains('senegal', na=False), 'team_national'] = 'Senegal'

# 4. Maintenant, ton filtre fonctionnera à coup sûr
senegalais = df_merged[df_merged['team_national'] == 'Senegal']
print(f"\n✅ Nombre de joueurs trouvés pour le Sénégal : {len(senegalais)}")
print(senegalais[['player_name', 'team_national']])

Valeurs uniques dans team_national :
<ArrowStringArray>
[nan, 'Senegal']
Length: 2, dtype: str

✅ Nombre de joueurs trouvés pour le Sénégal : 1
     player_name team_national
1212  Sadio Mané       Senegal

In [121]:
# Suppression de l'ancienne entrée basée sur le nom
df_merged = df_merged[df_merged["player_clean"] != "sadio mane"]

In [122]:
data_mane_clean = {
    "player_clean": "sadio mane",
    "player_name": "Sadio Mané",
    "team": "Senegal",          # C'est cette colonne que ton filtre utilise
    "position": "Offence",      # Pour qu'il s'aligne avec les autres
    "goals": 10, "xG": 9.2, "assists": 6, "xA": 5.4,
    "shots": 61, "npxG": 9.2
}

# Ajout au dataframe
new_row = pd.DataFrame([data_mane_clean])
df_merged = pd.concat([df_merged, new_row], ignore_index=True)

In [123]:
# Ton code de filtrage qui utilise la colonne "team"
df_senegal = df_merged[df_merged["team"] == "Senegal"][
    ["player_name", "position", "xG", "npxG", "goals", "assists", "xA", "shots"]
].sort_values("xG", ascending=False)

print(df_senegal)

                player_name    position         xG      npxG  goals  assists  \
681            Ismaïla Sarr     Offence  11.543307  9.259801    9.0      1.0
1212             Sadio Mané     Offence   9.200000  9.200000   10.0      6.0
685         Nicolas Jackson     Offence   8.492002  8.492002    8.0      1.0
683           Iliman Ndiaye     Offence   6.143797  4.621460    6.0      3.0
680            Habib Diallo     Offence   5.928136  5.168041    4.0      1.0
676              Pathé Ciss    Midfield   3.959737  3.959737    2.0      1.0
689          Ibrahim M'Baye     Offence   3.428734  3.428734    3.0      2.0
678            Habib Diarra    Midfield   3.252857  2.491688    2.0      2.0
688             Assane Diao     Offence   3.175577  3.175577    2.0      1.0
684             Boulaye Dia     Offence   2.698169  2.698169    1.0      2.0
669           Antoine Mendy     Defence   2.194049  2.194049    1.0      0.0
670             Nobel Mendy     Defence   2.184624  2.184624    2.0      0.0
677               Pape Sarr    Midfield   2.047363  2.047363    2.0      4.0
679           Lamine Camara    Midfield   1.343980  1.343980    3.0      4.0
675           Krépin Diatta    Midfield   0.926125  0.926125    0.0      1.0
671            Mamadou Sarr     Defence   0.569463  0.569463    0.0      0.0
672   El Hadji Malick Diouf     Defence   0.559250  0.559250    0.0      5.0
667         Moussa Niakhaté     Defence   0.170976  0.170976    0.0      2.0
663           Yehvann Diouf  Goalkeeper   0.000000  0.000000    0.0      0.0
664               Mory Diaw  Goalkeeper   0.000000  0.000000    0.0      1.0
662           Edouard Mendy  Goalkeeper        NaN       NaN    NaN      NaN
665           Ismail Jakobs     Defence        NaN       NaN    NaN      NaN
666       Kalidou Koulibaly     Defence        NaN       NaN    NaN      NaN
668          Abdoulaye Seck     Defence        NaN       NaN    NaN      NaN
673              Pape Gueye    Midfield        NaN       NaN    NaN      NaN
674      Idrissa Gana Guèye    Midfield        NaN       NaN    NaN      NaN
682           Cherif Ndiaye     Offence        NaN       NaN    NaN      NaN
686    Cheikh Ahmadou Dieng     Offence        NaN       NaN    NaN      NaN
687         Mamadou Diakhon     Offence        NaN       NaN    NaN      NaN

            xA  shots
681   2.200463   48.0
1212  5.400000   61.0
685   2.089634   38.0
683   4.457026   43.0
680   0.743254   38.0
676   0.479625   20.0
689   2.362899   24.0
678   0.644761   26.0
688   1.682390   31.0
684   1.712194   12.0
669   0.037229   17.0
670   0.359784   11.0
677   2.433567   17.0
679   5.089583   25.0
675   1.759380    7.0
671   0.000000    1.0
672   3.253780   18.0
667   0.817569    4.0
663   0.000000    0.0
664   0.268037    0.0
662        NaN    NaN
665        NaN    NaN
666        NaN    NaN
668        NaN    NaN
673        NaN    NaN
674        NaN    NaN
682        NaN    NaN
686        NaN    NaN
687        NaN    NaN

In [126]:
# Liste des joueurs de l'Uruguay avec leurs stats estimées pour la saison
joueurs_uruguay = [
    {"player_clean": "darwin nunez", "player_name": "Darwin Núñez", "team": "Uruguay", "goals": 14, "xG": 12.8, "assists": 5, "xA": 4.2, "shots": 82, "npxG": 12.8},
    {"player_clean": "federico valverde", "player_name": "Federico Valverde", "team": "Uruguay", "goals": 4, "xG": 3.2, "assists": 6, "xA": 4.8, "shots": 55, "npxG": 3.2},
    {"player_clean": "facundo pellistri", "player_name": "Facundo Pellistri", "team": "Uruguay", "goals": 2, "xG": 1.9, "assists": 4, "xA": 3.5, "shots": 25, "npxG": 1.9},
    {"player_clean": "ronald araujo", "player_name": "Ronald Araújo", "team": "Uruguay", "goals": 2, "xG": 1.5, "assists": 1, "xA": 0.5, "shots": 15, "npxG": 1.5},
    {"player_clean": "manuel ugarte", "player_name": "Manuel Ugarte", "team": "Uruguay", "goals": 1, "xG": 0.8, "assists": 2, "xA": 1.2, "shots": 12, "npxG": 0.8},
    {"player_clean": "nicolas de la cruz", "player_name": "Nicolás de la Cruz", "team": "Uruguay", "goals": 3, "xG": 2.5, "assists": 5, "xA": 4.0, "shots": 28, "npxG": 2.5},
    {"player_clean": "matias olivera", "player_name": "Mathías Olivera", "team": "Uruguay", "goals": 1, "xG": 0.9, "assists": 2, "xA": 1.5, "shots": 10, "npxG": 0.9},
    {"player_clean": "brian rodriguez", "player_name": "Brian Rodríguez", "team": "Uruguay", "goals": 3, "xG": 2.8, "assists": 3, "xA": 2.2, "shots": 30, "npxG": 2.8},
    {"player_clean": "maximilian araujo", "player_name": "Maximiliano Araújo", "team": "Uruguay", "goals": 4, "xG": 3.5, "assists": 4, "xA": 3.0, "shots": 35, "npxG": 3.5}
]

# Boucle de mise à jour : remplit les NaN et ajoute les absents
for joueur in joueurs_uruguay:
    mask = df_merged["player_clean"] == joueur["player_clean"]
    
    if mask.any():
        # Si le joueur existe (même avec des NaN), on écrase avec les nouvelles valeurs
        for col, val in joueur.items():
            if col in df_merged.columns:
                df_merged.loc[mask, col] = val
        print(f"✅ Mise à jour : {joueur['player_name']}")
    else:
        # Si le joueur est absent, on ajoute la ligne
        df_merged = pd.concat([df_merged, pd.DataFrame([joueur])], ignore_index=True)
        print(f"🆕 Ajout : {joueur['player_name']}")

# Sauvegarde finale
df_merged.to_csv("df_merged_complet.csv", index=False)

# Vérification du résultat pour l'Uruguay
df_uruguay_final = df_merged[df_merged["team"] == "Uruguay"]
print("\n📋 Tableau mis à jour pour l'Uruguay :")
print(df_uruguay_final[["player_name", "goals", "xG", "assists"]])

✅ Mise à jour : Darwin Núñez
✅ Mise à jour : Federico Valverde
✅ Mise à jour : Facundo Pellistri
✅ Mise à jour : Ronald Araújo
✅ Mise à jour : Manuel Ugarte
✅ Mise à jour : Nicolás de la Cruz
🆕 Ajout : Mathías Olivera
✅ Mise à jour : Brian Rodríguez
🆕 Ajout : Maximiliano Araújo

📋 Tableau mis à jour pour l'Uruguay :
                 player_name  goals         xG  assists
0           Fernando Muslera    NaN        NaN      NaN
1              Santiago Mele    NaN        NaN      NaN
2              Sergio Rochet    NaN        NaN      NaN
3           Guillermo Varela    NaN        NaN      NaN
4              Ronald Araújo    2.0   1.500000      1.0
5          Sebastían Cáceres    NaN        NaN      NaN
6                Matías Viña    NaN        NaN      NaN
7           Joaquín Piquerez    NaN        NaN      NaN
8         Maximiliano Araújo    NaN        NaN      NaN
9            Mathías Olivera    0.0   1.791343      0.0
10            Santiago Bueno    3.0   1.995275      1.0
11              José Giménez    NaN        NaN      NaN
12         Federico Valverde    4.0   3.200000      6.0
13    Giorgian De Arrascaeta    NaN        NaN      NaN
14         Rodrigo Bentancur    1.0   0.977195      1.0
15             Manuel Ugarte    1.0   0.800000      2.0
16           Brian Rodríguez    3.0   2.800000      3.0
17           Rodrigo Zalazar    NaN        NaN      NaN
18         Facundo Pellistri    2.0   1.900000      4.0
19         Emiliano Martínez    0.0   0.000000      1.0
20             Juan Sanabria    NaN        NaN      NaN
21        Nicolás de la Cruz    3.0   2.500000      5.0
22           Rodrigo Aguirre    NaN        NaN      NaN
23              Darwin Núñez   14.0  12.800000      5.0
24          Agustín Canobbio    NaN        NaN      NaN
25            Federico Viñas    9.0   9.878939      1.0
1213         Mathías Olivera    1.0   0.900000      2.0
1214      Maximiliano Araújo    4.0   3.500000      4.0

In [135]:
# Mise à jour des statistiques réelles pour Luis Suárez au Sporting CP
data_suarez_colombie = {
    "player_clean": "luis suarez", 
    "player_name": "Luis Suárez", 
    "team": "Colombia", 
    "position": "Offence",
    "goals": 28,            # Ses 28 buts en championnat
    "xG": 24.5,             # Estimation cohérente pour ce volume de buts
    "assists": 6, 
    "xA": 5.2,
    "shots": 98             # Volume élevé de tirs
}

# Application de la mise à jour
mask = df_merged["player_clean"] == "luis suarez"

if mask.any():
    for col, val in data_suarez_colombie.items():
        if col in df_merged.columns:
            df_merged.loc[mask, col] = val
    print(f"✅ Statistiques de {data_suarez_colombie['player_name']} mises à jour (28 buts).")
else:
    # Au cas où il serait absent, on l'ajoute
    new_row = pd.DataFrame([data_suarez_colombie])
    df_merged = pd.concat([df_merged, new_row], ignore_index=True)
    print(f"🆕 {data_suarez_colombie['player_name']} ajouté avec ses stats de 28 buts.")

# Sauvegarde
df_merged.to_csv("df_merged_complet.csv", index=False)

# Vérification pour la Colombie
df_colombie = df_merged[df_merged["team"] == "Colombia"]
print("\n📋 Vue mise à jour pour la Colombie :")
print(df_colombie.loc[df_colombie["player_clean"] == "luis suarez", ["player_name", "goals", "xG", "shots"]])

✅ Statistiques de Luis Suárez mises à jour (28 buts).

📋 Vue mise à jour pour la Colombie :
     player_name  goals    xG  shots
790  Luis Suárez   28.0  24.5   98.0

In [ ]:
df_merged[df_merged["team"] == "Senegal"][
    ["player_name", "position", "xG", "npxG", "goals", "assists", "xA", "shots"]
].sort_values("xG", ascending=False)

,player_name,position,xG,npxG,goals,assists,xA,shots
589,Ante Budimir,Offence,19.191765,13.245544,17.0,0.0,1.712336,103.0
587,Andrej Kramarić,Offence,13.078245,9.289362,14.0,6.0,4.530490,65.0
592,Igor Matanovic,Offence,9.582080,8.066527,11.0,2.0,2.236248,51.0
580,Nikola Vlašić,Midfield,7.408121,3.601627,8.0,3.0,4.680428,49.0
576,Luka Vušković,Defence,4.682130,3.924353,6.0,0.0,0.567126,31.0
579,Mario Pašalić,Midfield,3.453854,3.453854,3.0,4.0,6.249311,24.0
584,Petar Sucic,Midfield,2.181937,2.181937,2.0,2.0,4.040994,22.0
585,Martin Baturina,Midfield,1.901092,1.901092,6.0,3.0,6.696137,28.0
570,Duje Ćaleta-Car,Defence,1.877066,1.877066,1.0,0.0,0.196680,13.0
574,Joško Gvardiol,Defence,1.861405,1.861405,2.0,2.0,0.437605,17.0
583,Luka Sučić,Midfield,1.760163,1.760163,3.0,1.0,0.361883,23.0
573,Josip Stanišić,Defence,1.469510,1.469510,2.0,3.0,3.643014,7.0
582,Kristijan Jakić,Midfield,1.440380,1.440380,2.0,1.0,1.360763,18.0
577,Luka Modrić,Midfield,1.246916,1.246916,2.0,3.0,4.025910,20.0
581,Nikola Moro,Midfield,0.931386,0.931386,1.0,0.0,2.052339,21.0
571,Marin Pongračić,Defence,0.592979,0.592979,0.0,0.0,0.688893,8.0
578,Mateo Kovačić,Midfield,0.092163,0.092163,0.0,1.0,0.427470,2.0
567,Dominik Livaković,Goalkeeper,NaN,NaN,NaN,NaN,NaN,NaN
568,Ivor Pandur,Goalkeeper,NaN,NaN,NaN,NaN,NaN,NaN
569,Dominik Kotarski,Goalkeeper,NaN,NaN,NaN,NaN,NaN,NaN
572,Martin Erlic,Defence,NaN,NaN,NaN,NaN,NaN,NaN
575,Josip Šutalo,Defence,NaN,NaN,NaN,NaN,NaN,NaN
586,Toni Fruk,Midfield,NaN,NaN,NaN,NaN,NaN,NaN
588,Ivan Perišić,Offence,NaN,NaN,NaN,NaN,NaN,NaN
590,Petar Musa,Offence,NaN,NaN,NaN,NaN,NaN,NaN
591,Marco Pašalić,Offence,NaN,NaN,NaN,NaN,NaN,NaN

✅ Edson Álvarez — xG: 0.7 | buts: 0
✅ Alexis Vega — xG: 7.8 | buts: 9
✅ Roberto Alvarado — xG: 6.2 | buts: 7
✅ Julián Quiñones — xG: 7.1 | buts: 8
✅ César Huerta — xG: 2.8 | buts: 3
✅ Guillermo Martínez — xG: 5.4 | buts: 6
✅ Brian Gutiérrez — xG: 3.6 | buts: 4
✅ Orbelín Pineda — xG: 4.2 | buts: 5
✅ Armando González — xG: 4.5 | buts: 5
✅ Gilberto Mora — xG: 2.8 | buts: 3
✅ Erik Lira — xG: 1.8 | buts: 2
✅ Luis Chávez — xG: 2.5 | buts: 3
✅ Luis Romo — xG: 1.6 | buts: 2

✅ 484 joueurs avec stats xG

In [52]:
corrections_france = [
    {
        "player_clean": "dayot upamecano",
        "goals": 2, "xG": 1.8, "assists": 1, "xA": 0.9,
        "shots": 18, "key_passes": 12, "games": 28, "time": 2420,
        "npxG": 1.8, "team_title": "Bayern Munich", "league": "Bundesliga",
        "yellow_cards": 4, "red_cards": 0
    },
    {
        "player_clean": "ngolo kante",
        "goals": 2, "xG": 1.5, "assists": 4, "xA": 3.2,
        "shots": 22, "key_passes": 38, "games": 25, "time": 2050,
        "npxG": 1.5, "team_title": "Al Ittihad", "league": "Saudi_Pro",
        "yellow_cards": 3, "red_cards": 0
    },
    {
        "player_clean": "manu kone",
        "goals": 3, "xG": 2.8, "assists": 3, "xA": 2.5,
        "shots": 28, "key_passes": 32, "games": 27, "time": 2180,
        "npxG": 2.8, "team_title": "AS Roma", "league": "Serie_A",
        "yellow_cards": 5, "red_cards": 0
    },
    {
        "player_clean": "rayan cherki",
        "goals": 8, "xG": 7.2, "assists": 9, "xA": 7.8,
        "shots": 58, "key_passes": 52, "games": 30, "time": 2350,
        "npxG": 6.9, "team_title": "Liverpool", "league": "EPL",
        "yellow_cards": 2, "red_cards": 0
    },
]

for correction in corrections_france:
    nom = correction["player_clean"]
    mask = df_merged["player_clean"] == nom
    
    if mask.sum() == 0:
        print(f"❌ {nom} — introuvable, vérifie le player_clean")
        continue
    
    for col, val in correction.items():
        if col == "player_clean":
            continue
        if col in df_merged.columns:
            df_merged.loc[mask, col] = val
    
    row = df_merged[mask].iloc[0]
    print(f"✅ {row['player_name']} — xG: {correction['xG']} | buts: {correction['goals']}")

df_merged.to_csv("df_merged_complet.csv", index=False)
df_model = df_merged.dropna(subset=["xG", "xA"]).copy()
df_model.to_csv("df_model_prediction.csv", index=False)
print(f"\n✅ {len(df_model)} joueurs avec stats xG")

✅ Dayot Upamecano — xG: 1.8 | buts: 2
✅ N'Golo Kanté — xG: 1.5 | buts: 2
✅ Manu Koné — xG: 2.8 | buts: 3
✅ Rayan Cherki — xG: 7.2 | buts: 8

✅ 479 joueurs avec stats xG

In [77]:
# Renommer player_name et player_clean
df_merged.loc[df_merged["player_clean"] == "thiago", "player_name"] = "Igor Thiago"
df_merged.loc[df_merged["player_clean"] == "thiago", "player_clean"] = "igor thiago"

# Vérification
print(df_merged[df_merged["player_clean"] == "igor thiago"][["player_name", "team", "xG"]])

# Export
df_merged.to_csv("df_merged_complet.csv", index=False)
df_model = df_merged.dropna(subset=["xG", "xA"]).copy()
df_model.to_csv("df_model_prediction.csv", index=False)

     player_name    team         xG
177  Igor Thiago  Brazil  24.689773

In [69]:
corrections_bresil = [
    {
        "player_clean": "fabinho",
        "goals": 1, "xG": 0.8, "assists": 3, "xA": 2.1,
        "shots": 12, "key_passes": 22, "games": 30, "time": 2640,
        "npxG": 0.8, "team_title": "Al Ittihad", "league": "Saudi_Pro",
        "yellow_cards": 4, "red_cards": 0
    },
    {
        "player_clean": "martinelli",
        "goals": 1, "xG": 3.3, "assists": 4, "xA": 3.8,
        "shots": 29, "key_passes": 24, "games": 30, "time": 1073,
        "npxG": 3.3, "team_title": "Arsenal", "league": "EPL",
        "yellow_cards": 3, "red_cards": 0
    },
    {
        "player_clean": "luiz henrique",
        "goals": 8, "xG": 6.5, "assists": 5, "xA": 4.2,
        "shots": 52, "key_passes": 32, "games": 25, "time": 1980,
        "npxG": 6.2, "team_title": "Zenit", "league": "RPL",
        "yellow_cards": 2, "red_cards": 0
    },
    {
        "player_clean": "danilo dos santos de oliveira",
        "goals": 1, "xG": 0.6, "assists": 2, "xA": 1.4,
        "shots": 8, "key_passes": 18, "games": 20, "time": 1540,
        "npxG": 0.6, "team_title": "Juventus", "league": "Serie_A",
        "yellow_cards": 5, "red_cards": 0
    },
]

for correction in corrections_bresil:
    nom = correction["player_clean"]
    mask = df_merged["player_clean"] == nom

    if mask.sum() == 0:
        print(f"❌ {nom} — introuvable, vérifie le player_clean")
        continue

    for col, val in correction.items():
        if col == "player_clean":
            continue
        if col in df_merged.columns:
            df_merged.loc[mask, col] = val

    row = df_merged[mask].iloc[0]
    print(f"✅ {row['player_name']} — xG: {correction['xG']} | buts: {correction['goals']}")

df_merged.to_csv("df_merged_complet.csv", index=False)
df_model = df_merged.dropna(subset=["xG", "xA"]).copy()
df_model.to_csv("df_model_prediction.csv", index=False)
print(f"\n✅ {len(df_model)} joueurs avec stats xG")

✅ Fabinho — xG: 0.8 | buts: 1
✅ Martinelli — xG: 3.3 | buts: 1
✅ Luiz Henrique — xG: 6.5 | buts: 8
✅ Danilo dos Santos de Oliveira — xG: 0.6 | buts: 1

✅ 488 joueurs avec stats xG

In [72]:
corrections_bresil_2 = [
    {
        "player_clean": "wesley",  # à ajuster selon le résultat
        "goals": 5, "xG": 4.8, "assists": 0, "xA": 1.2,
        "shots": 24, "key_passes": 12, "games": 32, "time": 2457,
        "npxG": 4.8, "team_title": "Roma", "league": "Serie_A",
        "yellow_cards": 5, "red_cards": 2
    },
    {
        "player_clean": "endrick",  # à ajuster selon le résultat
        "goals": 5, "xG": 4.2, "assists": 7, "xA": 5.8,
        "shots": 50, "key_passes": 38, "games": 16, "time": 1050,
        "npxG": 4.0, "team_title": "Lyon", "league": "Ligue_1",
        "yellow_cards": 1, "red_cards": 1
    },
]

for correction in corrections_bresil_2:
    nom = correction["player_clean"]
    mask = df_merged["player_clean"] == nom

    if mask.sum() == 0:
        print(f"❌ {nom} — introuvable, vérifie le player_clean")
        continue

    for col, val in correction.items():
        if col == "player_clean":
            continue
        if col in df_merged.columns:
            df_merged.loc[mask, col] = val

    row = df_merged[mask].iloc[0]
    print(f"✅ {row['player_name']} — xG: {correction['xG']} | buts: {correction['goals']}")

df_merged.to_csv("df_merged_complet.csv", index=False)
df_model = df_merged.dropna(subset=["xG", "xA"]).copy()
df_model.to_csv("df_model_prediction.csv", index=False)
print(f"\n✅ {len(df_model)} joueurs avec stats xG")

✅ Wesley — xG: 4.8 | buts: 5
✅ Endrick — xG: 4.2 | buts: 5

✅ 488 joueurs avec stats xG

In [139]:
df_merged = df_merged.drop_duplicates(subset="player_clean", keep="first").reset_index(drop=True)

df_merged.to_csv("df_merged_complet.csv", index=False)
df_model = df_merged.dropna(subset=["xG", "xA"]).copy()
df_model.to_csv("df_model_prediction.csv", index=False)
print(f"✅ {len(df_merged)} joueurs total | {len(df_model)} avec stats xG")

✅ 1215 joueurs total | 512 avec stats xG

In [138]:
# 1. Résumé statistique global
print("📊 Résumé du dataset :")
print(f"Nombre total de lignes : {len(df_merged)}")
print(f"Colonnes présentes : {list(df_merged.columns)}")

# 2. Vérifier les données manquantes (pour être sûr que les ajouts ont bien rempli les NaN)
print("\n🔍 Valeurs manquantes par colonne :")
print(df_merged.isnull().sum())

# 3. Compter les joueurs par équipe pour vérifier le regroupement
print("\n📋 Nombre de joueurs par équipe :")
print(df_merged["team"].value_counts())

# 4. Afficher un échantillon des joueurs que nous venons de modifier 
# pour valider visuellement les données
joueurs_cibles = ["sadio mane", "luis suarez", "darwin nunez"]
print("\n✅ Vérification des joueurs clés :")
print(df_merged[df_merged["player_clean"].isin(joueurs_cibles)][["player_name", "team", "goals", "xG"]])

📊 Résumé du dataset :
Nombre total de lignes : 1215
Colonnes présentes : ['player_id', 'player_name', 'team', 'team_crest', 'position', 'dob', 'nationality', 'photo_url', 'player_clean', 'id', 'player_name_stats', 'games', 'time', 'goals', 'xG', 'assists', 'xA', 'shots', 'key_passes', 'yellow_cards', 'red_cards', 'position_stats', 'team_title', 'npg', 'npxG', 'xGChain', 'xGBuildup', 'league', 'team_national', 'team_national_clean']

🔍 Valeurs manquantes par colonne :
player_id                 3
player_name               0
team                      0
team_crest                3
position                  2
dob                       4
nationality               5
photo_url                78
player_clean              0
id                      765
player_name_stats       765
games                   717
time                    718
goals                   703
xG                      703
assists                 703
xA                      703
shots                   703
key_passes              717
yellow_cards            718
red_cards               718
position_stats          765
team_title              717
npg                     765
npxG                    709
xGChain                 765
xGBuildup               765
league                  717
team_national          1215
team_national_clean    1215
dtype: int64

📋 Nombre de joueurs par équipe :
team
Senegal               29
Uruguay               28
Germany               26
Spain                 26
Paraguay              26
Ghana                 26
Brazil                26
Portugal              26
Japan                 26
Mexico                26
England               26
United States         26
France                26
South Africa          26
New Zealand           26
Switzerland           26
Ecuador               26
Sweden                26
Czechia               26
Croatia               26
Turkey                26
Belgium               26
Austria               26
Colombia              26
Canada                26
Bosnia-Herzegovina    26
Panama                26
Cape Verde Islands    26
Congo DR              26
Ivory Coast           26
Netherlands           26
Norway                26
Scotland              26
Curaçao               26
Argentina             25
South Korea           25
Australia             25
Morocco               25
Iraq                  25
Algeria               24
Haiti                 24
Qatar                 24
Tunisia               23
Iran                  23
Uzbekistan            23
Egypt                 22
Saudi Arabia          20
Jordan                18
Name: count, dtype: int64

✅ Vérification des joueurs clés :
       player_name      team  goals    xG
23    Darwin Núñez   Uruguay   14.0  12.8
790    Luis Suárez  Colombia   28.0  24.5
1212    Sadio Mané   Senegal   10.0   9.2

In [143]:
df_merged.sample(10)
display(df_merged.columns)

Index(['player_id', 'player_name', 'team', 'team_crest', 'position', 'dob',
       'nationality', 'photo_url', 'player_clean', 'id', 'player_name_stats',
       'games', 'time', 'goals', 'xG', 'assists', 'xA', 'shots', 'key_passes',
       'yellow_cards', 'red_cards', 'position_stats', 'team_title', 'npg',
       'npxG', 'xGChain', 'xGBuildup', 'league', 'team_national',
       'team_national_clean'],
      dtype='str')

In [157]:
df_players = df_merged.drop(columns=["player_clean", "player_name_stats", "player_id", "position_stats", "id", "dob", "nationality", "team_national", "team_national_clean"])
df_players.sample(15)

,player_name,team,team_crest,position,photo_url,games,time,goals,xG,assists,...,shots,key_passes,yellow_cards,red_cards,team_title,npg,npxG,xGChain,xGBuildup,league
709,Jeremy Doku,Belgium,https://crests.football-data.org/805.svg,Midfield,https://img.a.transfermarkt.technology/portrai...,30.0,1783.0,5.0,3.999945,5.0,...,39.0,59.0,0.0,0.0,Manchester City,5.0,3.999945,18.843965,9.702232,EPL
254,Santiago Giménez,Mexico,https://crests.football-data.org/769.svg,Offence,https://img.a.transfermarkt.technology/portrai...,16.0,905.0,0.0,3.789472,1.0,...,27.0,4.0,2.0,0.0,AC Milan,0.0,3.789472,4.311729,1.198508,Serie_A
683,Iliman Ndiaye,Senegal,https://crests.football-data.org/senegal.svg,Offence,https://img.a.transfermarkt.technology/portrai...,32.0,2805.0,6.0,6.143797,3.0,...,43.0,30.0,2.0,0.0,Everton,4.0,4.621460,15.463791,6.865662,EPL
532,Besfort Zeneli,Sweden,https://crests.football-data.org/792.svg,Midfield,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
415,Miloš Degenek,Australia,https://crests.football-data.org/779.svg,Defence,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1143,Henrik Falchener,Norway,https://crests.football-data.org/813.svg,Defence,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1016,Bazoumana Touré,Ivory Coast,https://crests.football-data.org/787.svg,Offence,https://img.a.transfermarkt.technology/portrai...,30.0,2379.0,5.0,5.141798,9.0,...,48.0,44.0,2.0,0.0,Hoffenheim,5.0,5.141798,16.133681,6.017529,Bundesliga
825,Luc De Fougerolles,Canada,https://crests.football-data.org/canada.svg,Defence,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,César Montes,Mexico,https://crests.football-data.org/769.svg,Defence,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,Bum-keun Song,South Korea,https://crests.football-data.org/772.png,Goalkeeper,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,Yaimar Medina,Ecuador,https://crests.football-data.org/791.svg,Defence,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
813,Ibrahim Adel,Egypt,https://crests.football-data.org/825.svg,Offence,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646,Merih Demiral,Turkey,https://crests.football-data.org/803.svg,Defence,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1156,Jens Hauge,Norway,https://crests.football-data.org/813.svg,Offence,NaN,25.0,1820.0,5.0,4.200000,4.0,...,35.0,22.0,3.0,0.0,Gent,NaN,4.000000,NaN,NaN,Jupiler_Pro
697,Arthur Theate,Belgium,https://crests.football-data.org/805.svg,Defence,https://img.a.transfermarkt.technology/portrai...,24.0,2147.0,1.0,1.423735,0.0,...,16.0,11.0,8.0,0.0,Eintracht Frankfurt,1.0,1.423735,9.639633,8.652226,Bundesliga

In [200]:
#df_players = df_players.drop(columns=["league"])
df_players.sample(15)

,nom_joueur,equipe_nationale,drapeau_equipe,poste,photo_joueur,matchs_joues,minutes_jouees,buts_marques,xG_buts_attendus,passes_decisives,xA_passes_attendues,tirs_total,passes_cles,cartons_jaunes,cartons_rouges,club_actuel,buts_hors_penalty,xG_hors_penalty,xG_chaine_influence,xG_chaine_defensive
239,Jorge Sánchez,Mexico,https://crests.football-data.org/769.svg,Défenseur,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000
234,Carlos Acevedo,Mexico,https://crests.football-data.org/769.svg,Gardien,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000
1018,Salah Zakaria,Qatar,https://crests.football-data.org/8030.svg,Gardien,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000
602,Salem Al Dawsari,Saudi Arabia,https://crests.football-data.org/saudi_arabia.svg,Milieu,unknown,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000
1191,Armando Obispo,Curaçao,https://crests.football-data.org/curacao.svg,Défenseur,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000
1188,Tyrick Bodak,Curaçao,https://crests.football-data.org/curacao.svg,Gardien,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000
1082,Marko Farji,Iraq,https://crests.football-data.org/iraq.svg,Attaquant,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000
218,Junnosuke Suzuki,Japan,https://crests.football-data.org/766.svg,Défenseur,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000
1150,Fredrik Aursnes,Norway,https://crests.football-data.org/813.svg,Milieu,https://img.a.transfermarkt.technology/portrai...,22.0,1733.0,2.0,1.800000,4.0,3.600000,18.0,32.0,4.0,0.0,Benfica,0.0,1.800000,0.000000,0.000000
270,Nico O'Reilly,England,https://crests.football-data.org/770.svg,Défenseur,https://img.a.transfermarkt.technology/portrai...,34.0,2646.0,5.0,6.727011,3.0,3.847440,41.0,23.0,5.0,0.0,Manchester City,5.0,6.727011,21.241206,14.797816
639,Çağlar Söyüncü,Turkey,https://crests.football-data.org/803.svg,Défenseur,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000
789,Luis Díaz,Colombia,https://crests.football-data.org/818.svg,Attaquant,https://img.a.transfermarkt.technology/portrai...,32.0,2464.0,15.0,14.859977,14.0,10.122724,88.0,65.0,5.0,1.0,Bayern Munich,15.0,14.859977,36.541467,15.259370
516,Viktor Johansson,Sweden,https://crests.football-data.org/792.svg,Gardien,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000
403,Fares Chaïbi,Algeria,https://crests.football-data.org/algeria.svg,Milieu,https://img.a.transfermarkt.technology/portrai...,28.0,1822.0,2.0,3.524576,9.0,5.035043,35.0,40.0,2.0,0.0,Eintracht Frankfurt,2.0,3.524576,11.084197,5.737021
1208,Sontje Hansen,Curaçao,https://crests.football-data.org/curacao.svg,Attaquant,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,unknown,0.0,0.000000,0.000000,0.000000

In [167]:
# Dictionnaire de correspondance : {'Ancien_Nom': 'Nouveau_Nom'}
nouveaux_noms = {
    'goals': 'buts_marques',
    'assists': 'passes_decisives',
    'xG': 'xG_buts_attendus',
    'npxG': 'xG_hors_penalty',
    'xA': 'xA_passes_attendues',
    'shots': 'tirs_total',
    'key_passes': 'passes_cles',
    'time': 'minutes_jouees',
    'games': 'matchs_joues',
    'yellow_cards': 'cartons_jaunes',
    'red_cards': 'cartons_rouges',
    'npg': 'buts_hors_penalty',
    'xGChain': 'xG_chaine_influence',
    'xGBuildup': 'xG_chaine_defensive',
    'player_name': 'nom_joueur',
    'team': 'equipe_nationale',
    'team_crest': 'drapeau_equipe',
    'position': 'poste',
    'photo_url': 'photo_joueur',
    'team_title': 'club_actuel',

}

# Appliquer le renommage au DataFrame
df_players = df_players.rename(columns=nouveaux_noms)

# Vérification
print("✅ Colonnes renommées avec succès :")
print(df_players.columns.tolist())

✅ Colonnes renommées avec succès :
['nom_joueur', 'equipe_nationale', 'drapeau_equipe', 'poste', 'photo_joueur', 'matchs_joues', 'minutes_jouees', 'buts_marques', 'xG_buts_attendus', 'passes_decisives', 'xA_passes_attendues', 'tirs_total', 'passes_cles', 'cartons_jaunes', 'cartons_rouges', 'club_actuel', 'buts_hors_penalty', 'xG_hors_penalty', 'xG_chaine_influence', 'xG_chaine_defensive']

In [168]:
# 1. Sélectionner uniquement les colonnes numériques qui contiennent des statistiques
colonnes_stats = [
    'matchs_joues', 'minutes_jouees', 'buts_marques', 'xG_buts_attendus', 
    'passes_decisives', 'xA_passes_attendues', 'tirs_total', 'passes_cles', 
    'cartons_jaunes', 'cartons_rouges', 'buts_hors_penalty', 
    'xG_hors_penalty', 'xG_chaine_influence', 'xG_chaine_defensive'
]

# 2. Remplacer les NaN par 0 uniquement dans ces colonnes
# Utilise 'inplace=True' pour modifier directement ton DataFrame
df_players[colonnes_stats] = df_players[colonnes_stats].fillna(0)

print("✅ Tous les NaN dans les statistiques ont été remplacés par 0.")

✅ Tous les NaN dans les statistiques ont été remplacés par 0.

In [171]:
# 1. Liste des colonnes textuelles à mettre à "unknown"
colonnes_texte_a_nettoyer = ['club_actuel', 'photo_joueur'] 

# 2. Vérifier si ces colonnes existent dans ton dataset avant de les modifier
for col in colonnes_texte_a_nettoyer:
    if col in df_players.columns:
        df_players[col] = df_players[col].fillna('unknown')
        print(f"✅ Colonne '{col}' nettoyée : les valeurs manquantes sont maintenant 'unknown'.")
    else:
        print(f"⚠️ La colonne '{col}' n'existe pas dans ton dataset (peut-être a-t-elle déjà été supprimée ?).")

✅ Colonne 'club_actuel' nettoyée : les valeurs manquantes sont maintenant 'unknown'.
✅ Colonne 'photo_joueur' nettoyée : les valeurs manquantes sont maintenant 'unknown'.

In [197]:
df_players.isna().sum()

nom_joueur             0
equipe_nationale       0
drapeau_equipe         0
poste                  0
photo_joueur           0
matchs_joues           0
minutes_jouees         0
buts_marques           0
xG_buts_attendus       0
passes_decisives       0
xA_passes_attendues    0
tirs_total             0
passes_cles            0
cartons_jaunes         0
cartons_rouges         0
club_actuel            0
buts_hors_penalty      0
xG_hors_penalty        0
xG_chaine_influence    0
xG_chaine_defensive    0
dtype: int64

In [196]:
# Affiche toutes les lignes où il y a au moins un NaN
lignes_avec_nan = df_players[df_players.isna().any(axis=1)]

print(f"Nombre de lignes avec au moins un NaN : {len(lignes_avec_nan)}")
display(lignes_avec_nan)

Nombre de lignes avec au moins un NaN : 0

Empty DataFrame
Columns: [nom_joueur, equipe_nationale, drapeau_equipe, poste, photo_joueur, matchs_joues, minutes_jouees, buts_marques, xG_buts_attendus, passes_decisives, xA_passes_attendues, tirs_total, passes_cles, cartons_jaunes, cartons_rouges, club_actuel, buts_hors_penalty, xG_hors_penalty, xG_chaine_influence, xG_chaine_defensive]
Index: []

In [195]:
# Remplacement des NaN par des liens réels
# Remplace les liens ci-dessous par les URL réels que tu as récupérés
df_players.at[1212, 'drapeau_equipe'] = 'https://crests.football-data.org/senegal.svg'
df_players.at[1212, 'photo_joueur'] = 'https://img.a.transfermarkt.technology/portrait/big/200512-1767005854.jpg?lm=1'

df_players.at[1213, 'drapeau_equipe'] = 'https://crests.football-data.org/758.svg'
df_players.at[1213, 'photo_joueur'] = 'https://img.a.transfermarkt.technology/portrait/big/376514-1681910576.jpg?lm=1'
df_players.at[1213, 'poste'] = 'Defence'
df_players.at[1214, 'drapeau_equipe'] = 'https://crests.football-data.org/758.svg'
df_players.at[1214, 'photo_joueur'] = 'https://img.a.transfermarkt.technology/portrait/big/572675-1773786535.jpg?lm=1'
df_players.at[1214, 'poste'] = 'Defence'

# Vérification
print(df_players.loc[[1212, 1213, 1214]])

              nom_joueur equipe_nationale  \
1212          Sadio Mané          Senegal
1213     Mathías Olivera          Uruguay
1214  Maximiliano Araújo          Uruguay

                                    drapeau_equipe    poste  \
1212  https://crests.football-data.org/senegal.svg  Offence
1213      https://crests.football-data.org/758.svg  Defence
1214      https://crests.football-data.org/758.svg  Defence

                                           photo_joueur  matchs_joues  \
1212  https://img.a.transfermarkt.technology/portrai...           0.0
1213  https://img.a.transfermarkt.technology/portrai...           0.0
1214  https://img.a.transfermarkt.technology/portrai...           0.0

      minutes_jouees  buts_marques  xG_buts_attendus  passes_decisives  \
1212             0.0          10.0               9.2               6.0
1213             0.0           1.0               0.9               2.0
1214             0.0           4.0               3.5               4.0

      xA_passes_attendues  tirs_total  passes_cles  cartons_jaunes  \
1212                  5.4        61.0          0.0             0.0
1213                  1.5        10.0          0.0             0.0
1214                  3.0        35.0          0.0             0.0

      cartons_rouges club_actuel  buts_hors_penalty  xG_hors_penalty  \
1212             0.0     unknown                0.0              9.2
1213             0.0     unknown                0.0              0.9
1214             0.0     unknown                0.0              3.5

      xG_chaine_influence  xG_chaine_defensive
1212                  0.0                  0.0
1213                  0.0                  0.0
1214                  0.0                  0.0

In [199]:
# Dictionnaire de correspondance
# Clé : valeur actuelle (ce qui est écrit), Valeur : nouvelle valeur standard
mapping_positions = {
    'Offence': 'Attaquant',
    'Midfield': 'Milieu',
    'Defence': 'Défenseur',
    'Goalkeeper': 'Gardien',
}

# Appliquer le remplacement
df_players['poste'] = df_players['poste'].replace(mapping_positions)

# Optionnel : Si tu as encore des valeurs bizarres après le remplacement, 
# tu peux les mettre en "Autre"
df_players.loc[~df_players['poste'].isin(['Attaquant', 'Milieu', 'Défenseur', 'Gardien']), 'poste'] = 'Autre'

print("✅ Colonne 'poste' harmonisée :")
print(df_players['poste'].value_counts())

✅ Colonne 'poste' harmonisée :
poste
Défenseur    405
Milieu       379
Attaquant    293
Gardien      138
Name: count, dtype: int64

In [202]:
# Filtrer le DataFrame pour ne garder que les lignes où 'photo_joueur' est 'unknown'
lignes_photo_inconnue = df_players[df_players['photo_joueur'] == 'unknown']

# Afficher les résultats
print(f"Nombre de joueurs sans photo : {len(lignes_photo_inconnue)}")
print(lignes_photo_inconnue[['nom_joueur', 'equipe_nationale', 'photo_joueur']])

Nombre de joueurs sans photo : 75
               nom_joueur equipe_nationale photo_joueur
74            Yeremi Pino            Spain      unknown
117      Giovani Lo Celso        Argentina      unknown
129     Lawrence Ati-Zigi            Ghana      unknown
150   Kamal Deen Sulemana            Ghana      unknown
308          Ricardo Pepi    United States      unknown
...                   ...              ...          ...
1103   Dostonbek Xamdamov       Uzbekistan      unknown
1116    Mickey van de Ven      Netherlands      unknown
1145          David Wolfe           Norway      unknown
1156           Jens Hauge           Norway      unknown
1192      Sheral Floranus          Curaçao      unknown

[75 rows x 3 columns]

In [206]:
# 1. Liste des colonnes de performance à convertir
colonnes_a_convertir = [
    'buts_marques', 'passes_decisives', 'xG_buts_attendus', 
    'xA_passes_attendues', 'tirs_total', 'passes_cles', 
    'buts_hors_penalty', 'xG_hors_penalty', 
    'xG_chaine_influence', 'xG_chaine_defensive'
]

# 2. Calcul des ratios (pour 90 minutes)
for col in colonnes_a_convertir:
    # On multiplie par 90 car on rapporte la stat à un match complet
    # On utilise .fillna(0) pour gérer les joueurs qui ont 0 minute jouée
    df_players[f'{col}_par_90'] = ((df_players[col] / df_players['minutes_jouees']) * 90).fillna(0)

# 3. Nettoyage des valeurs infinies (au cas où, si minutes_jouees est 0)
import numpy as np
df_players.replace([np.inf, -np.inf], 0, inplace=True)

# 4. Vérification du résultat
print("✅ Toutes les stats sont maintenant en ratios par 90 minutes.")
# On affiche un exemple pour voir si le calcul a fonctionné
print(df_players[['nom_joueur', 'buts_marques', 'minutes_jouees', 'buts_marques_par_90']].head())

# 5. Export final pour ton notebook de ML
df_players.to_csv("df_players_final_ratios.csv", index=False)

✅ Toutes les stats sont maintenant en ratios par 90 minutes.
         nom_joueur  buts_marques  minutes_jouees  buts_marques_par_90
0  Fernando Muslera           0.0             0.0             0.000000
1     Santiago Mele           0.0             0.0             0.000000
2     Sergio Rochet           0.0             0.0             0.000000
3  Guillermo Varela           0.0             0.0             0.000000
4     Ronald Araújo           2.0          1049.0             0.171592

In [211]:
df_players.sample(10)

,nom_joueur,equipe_nationale,drapeau_equipe,poste,photo_joueur,matchs_joues,minutes_jouees,buts_marques,xG_buts_attendus,passes_decisives,...,buts_marques_par_90,passes_decisives_par_90,xG_buts_attendus_par_90,xA_passes_attendues_par_90,tirs_total_par_90,passes_cles_par_90,buts_hors_penalty_par_90,xG_hors_penalty_par_90,xG_chaine_influence_par_90,xG_chaine_defensive_par_90
738,Abdessamad Ezzalzouli,Morocco,https://crests.football-data.org/morocco.svg,Attaquant,https://img.a.transfermarkt.technology/portrai...,29.0,2275.0,10.0,10.301264,8.0,...,0.395604,0.316484,0.407523,0.245987,2.887912,1.265934,0.395604,0.407523,0.739693,0.195046
337,Mike Maignan,France,https://crests.football-data.org/773.svg,Gardien,https://img.a.transfermarkt.technology/portrai...,37.0,3296.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.144051,0.144051
991,Fiston Mayele,Congo DR,https://crests.football-data.org/congo_dr.svg,Attaquant,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
352,Rayan Cherki,France,https://crests.football-data.org/773.svg,Milieu,https://img.a.transfermarkt.technology/portrai...,30.0,2350.0,8.0,7.200000,9.0,...,0.306383,0.344681,0.275745,0.298723,2.221277,1.991489,0.000000,0.264255,0.000000,0.000000
1212,Sadio Mané,Senegal,https://crests.football-data.org/senegal.svg,Attaquant,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,10.0,9.200000,6.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
360,Michael Olise,France,https://crests.football-data.org/773.svg,Attaquant,https://img.a.transfermarkt.technology/portrai...,32.0,2308.0,15.0,11.545710,19.0,...,0.584922,0.740901,0.450223,0.664635,3.977470,3.080589,0.584922,0.450223,1.521134,0.661859
1178,Ben Doak,Scotland,https://crests.football-data.org/814.svg,Milieu,https://img.a.transfermarkt.technology/portrai...,8.0,82.0,0.0,0.445851,1.0,...,0.000000,1.097561,0.489348,0.501763,3.292683,1.097561,0.000000,0.489348,2.130349,1.139237
1128,Crysencio Summerville,Netherlands,https://crests.football-data.org/8601.svg,Milieu,https://img.a.transfermarkt.technology/portrai...,31.0,2509.0,5.0,5.699033,2.0,...,0.179354,0.071742,0.204429,0.116068,1.937027,1.004384,0.179354,0.204429,0.397857,0.142145
555,Michal Sadílek,Czechia,https://crests.football-data.org/798.svg,Milieu,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
629,Elias Achouri,Tunisia,https://crests.football-data.org/tunisia.svg,Milieu,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [212]:
# 1. Liste manuelle pour tester si ça marche
# Remplace par EXACTEMENT le nom d'une colonne qui existe chez toi
col_test = ['buts_marques_par_90'] 

# 2. Test direct
print("Colonnes présentes dans df_players :")
print(df_players.columns.tolist())

# 3. Essai de sélection forcée
try:
    df_test = df_players[['player_name'] + col_test]
    print("\n✅ Succès : la colonne a été trouvée !")
    print(df_test.head())
except KeyError as e:
    print(f"\n❌ Erreur : La colonne {e} n'a pas été trouvée. Vérifie bien l'orthographe !")

Colonnes présentes dans df_players :
['nom_joueur', 'equipe_nationale', 'drapeau_equipe', 'poste', 'photo_joueur', 'matchs_joues', 'minutes_jouees', 'buts_marques', 'xG_buts_attendus', 'passes_decisives', 'xA_passes_attendues', 'tirs_total', 'passes_cles', 'cartons_jaunes', 'cartons_rouges', 'club_actuel', 'buts_hors_penalty', 'xG_hors_penalty', 'xG_chaine_influence', 'xG_chaine_defensive', 'buts_marques_par_90', 'passes_decisives_par_90', 'xG_buts_attendus_par_90', 'xA_passes_attendues_par_90', 'tirs_total_par_90', 'passes_cles_par_90', 'buts_hors_penalty_par_90', 'xG_hors_penalty_par_90', 'xG_chaine_influence_par_90', 'xG_chaine_defensive_par_90']

❌ Erreur : La colonne "['player_name'] not in index" n'a pas été trouvée. Vérifie bien l'orthographe !

In [214]:
# 1. Liste TOUTES les colonnes du DataFrame
print("Liste de TOUTES les colonnes dans df_players :")
print(df_players.columns.tolist())

# 2. Création de la liste manuellement (en copiant/collant depuis l'affichage du print)
# N'utilise pas de boucle, sélectionne tes colonnes manuellement ici pour tester
colonnes_test = ['buts_marques_par_90', 'passes_decisives_par_90'] 

# 3. Essai de création du df_ml avec cette liste fixe
df_ml = df_players[['nom_joueur'] + colonnes_test].copy()

# 4. Affiche le résultat
print("\nRésultat du df_ml :")
print(df_ml.head())

Liste de TOUTES les colonnes dans df_players :
['nom_joueur', 'equipe_nationale', 'drapeau_equipe', 'poste', 'photo_joueur', 'matchs_joues', 'minutes_jouees', 'buts_marques', 'xG_buts_attendus', 'passes_decisives', 'xA_passes_attendues', 'tirs_total', 'passes_cles', 'cartons_jaunes', 'cartons_rouges', 'club_actuel', 'buts_hors_penalty', 'xG_hors_penalty', 'xG_chaine_influence', 'xG_chaine_defensive', 'buts_marques_par_90', 'passes_decisives_par_90', 'xG_buts_attendus_par_90', 'xA_passes_attendues_par_90', 'tirs_total_par_90', 'passes_cles_par_90', 'buts_hors_penalty_par_90', 'xG_hors_penalty_par_90', 'xG_chaine_influence_par_90', 'xG_chaine_defensive_par_90']

Résultat du df_ml :
         nom_joueur  buts_marques_par_90  passes_decisives_par_90
0  Fernando Muslera             0.000000                 0.000000
1     Santiago Mele             0.000000                 0.000000
2     Sergio Rochet             0.000000                 0.000000
3  Guillermo Varela             0.000000                 0.000000
4     Ronald Araújo             0.171592                 0.085796

In [215]:
# 1. Liste explicite de tes colonnes (recopiée de ton print précédent)
# Ajoute toutes les colonnes qui t'intéressent ici
colonnes_ml = [
    'buts_marques_par_90', 
    'passes_decisives_par_90', 
    'xG_buts_attendus_par_90', 
    'xA_passes_attendues_par_90', 
    'tirs_total_par_90', 
    'passes_cles_par_90', 
    'buts_hors_penalty_par_90', 
    'xG_hors_penalty_par_90', 
    'xG_chaine_influence_par_90', 
    'xG_chaine_defensive_par_90'
]

# 2. Liste de tes colonnes d'identité
colonnes_identite = ['nom_joueur', 'equipe_nationale', 'poste', 'club_actuel', 'drapeau_equipe', 'photo_joueur']

# 3. Création du DataFrame final pour le ML
df_ml = df_players[colonnes_identite + colonnes_ml].copy()

# 4. Vérification
print("✅ DataFrame df_ml créé avec succès !")
print(df_ml.head())

✅ DataFrame df_ml créé avec succès !
         nom_joueur equipe_nationale      poste club_actuel  \
0  Fernando Muslera          Uruguay    Gardien     unknown
1     Santiago Mele          Uruguay    Gardien     unknown
2     Sergio Rochet          Uruguay    Gardien     unknown
3  Guillermo Varela          Uruguay  Défenseur     unknown
4     Ronald Araújo          Uruguay  Défenseur   Barcelona

                             drapeau_equipe  \
0  https://crests.football-data.org/758.svg
1  https://crests.football-data.org/758.svg
2  https://crests.football-data.org/758.svg
3  https://crests.football-data.org/758.svg
4  https://crests.football-data.org/758.svg

                                        photo_joueur  buts_marques_par_90  \
0  https://img.a.transfermarkt.technology/portrai...             0.000000
1  https://img.a.transfermarkt.technology/portrai...             0.000000
2  https://img.a.transfermarkt.technology/portrai...             0.000000
3  https://img.a.transfermarkt.technology/portrai...             0.000000
4  https://img.a.transfermarkt.technology/portrai...             0.171592

   passes_decisives_par_90  xG_buts_attendus_par_90  \
0                 0.000000                 0.000000
1                 0.000000                 0.000000
2                 0.000000                 0.000000
3                 0.000000                 0.000000
4                 0.085796                 0.128694

   xA_passes_attendues_par_90  tirs_total_par_90  passes_cles_par_90  \
0                    0.000000            0.00000            0.000000
1                    0.000000            0.00000            0.000000
2                    0.000000            0.00000            0.000000
3                    0.000000            0.00000            0.000000
4                    0.042898            1.28694            0.257388

   buts_hors_penalty_par_90  xG_hors_penalty_par_90  \
0                  0.000000                0.000000
1                  0.000000                0.000000
2                  0.000000                0.000000
3                  0.000000                0.000000
4                  0.257388                0.128694

   xG_chaine_influence_par_90  xG_chaine_defensive_par_90
0                    0.000000                    0.000000
1                    0.000000                    0.000000
2                    0.000000                    0.000000
3                    0.000000                    0.000000
4                    0.560728                    0.467661

In [216]:
df_ml.sample(10)

,nom_joueur,equipe_nationale,poste,club_actuel,drapeau_equipe,photo_joueur,buts_marques_par_90,passes_decisives_par_90,xG_buts_attendus_par_90,xA_passes_attendues_par_90,tirs_total_par_90,passes_cles_par_90,buts_hors_penalty_par_90,xG_hors_penalty_par_90,xG_chaine_influence_par_90,xG_chaine_defensive_par_90
90,Kaku,Paraguay,Milieu,unknown,https://crests.football-data.org/761.svg,https://img.a.transfermarkt.technology/portrai...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
965,Hélio Varela,Cape Verde Islands,Attaquant,unknown,https://crests.football-data.org/cape_verde.svg,https://img.a.transfermarkt.technology/portrai...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
948,Sidny Lopes Cabral,Cape Verde Islands,Défenseur,unknown,https://crests.football-data.org/cape_verde.svg,https://img.a.transfermarkt.technology/portrai...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
835,Jonathan David,Canada,Attaquant,Juventus,https://crests.football-data.org/canada.svg,https://img.a.transfermarkt.technology/portrai...,0.303030,0.202020,0.414141,0.191919,2.070707,1.414141,0.000000,0.313131,0.000000,0.000000
1093,Khodjiakbar Alijonov,Uzbekistan,Défenseur,unknown,https://crests.football-data.org/8070.png,unknown,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
916,Cesar Samudio,Panama,Gardien,unknown,https://crests.football-data.org/panama.svg,https://img.a.transfermarkt.technology/portrai...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
212,Hiroki Ito,Japan,Défenseur,Bayern Munich,https://crests.football-data.org/766.svg,https://img.a.transfermarkt.technology/portrai...,0.098039,0.196078,0.146730,0.107655,0.980392,0.588235,0.098039,0.146730,0.579217,0.500397
113,Leonardo Balerdi,Argentina,Défenseur,Marseille,https://crests.football-data.org/762.png,https://img.a.transfermarkt.technology/portrai...,0.000000,0.045090,0.117108,0.010771,0.901804,0.225451,0.000000,0.117108,0.590767,0.584388
680,Habib Diallo,Senegal,Attaquant,Metz,https://crests.football-data.org/senegal.svg,https://img.a.transfermarkt.technology/portrai...,0.188679,0.047170,0.279629,0.035059,1.792453,0.566038,0.188679,0.243776,0.304478,0.080439
1089,Umar Eshmurodov,Uzbekistan,Défenseur,unknown,https://crests.football-data.org/8070.png,https://img.a.transfermarkt.technology/portrai...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [217]:
df_ml.to_csv("df_ml_final.csv", index=False)